### ISSUE TITLE
Note for others: Support for newer components https://gist.github.com/clue/6ba091ed298b1ecec528a3a6c201a2d1

### ISSUE THREAD

**Issue by OctopusCloud** [clue/php-sse-react#9]
https://gist.github.com/clue/6ba091ed298b1ecec528a3a6c201a2d1
Here is a new implementation from clue for basic sse support with the new components. 

Im only dumping this here because this repo is the first result on google.

**Comment by clue** [comment]
Thanks @OctopusCloud, I guess it makes sense to leave this link up for now and I'll make sure to update this ticket once this repository is updated :+1:
